### ISSUE TITLE
Using Chartboost via SonarCocosHelper

### ISSUE THREAD

**Issue by hamburml** [SonarSystems/Cocos-Helper#1]
Hi!

I successfully added Chartboost with your Cocos Helper! Great!

Now I called SonarCocosHelper::Chartboost::showFullscreenAd();. After this call I am using the cocos2d-x director to replace the current Scene. Sadly the scene is replaced and after that the fullscreen ad is shown. The game itself isn't paused. How can i achieve that a) the ad is shown before the replace and b) the app is paused like it's when using admob.

Thanks!

**Comment by hamburml** [comment]
Same Issue with showVideoAd();

**Comment by SonarSystems** [comment]
For pausing we recommend you actually halt using Cocos2d-x code, sort of like a state machine.

For the other task try using a timer.
