### ISSUE TITLE
Crash when use Admod in iOS

### ISSUE THREAD

**Issue by hoangtaiki** [SonarSystems/Cocos-Helper#13]
2015-07-16 19:43:04.834 TestAndroid-mobile[9001:247857] -[GADInterstitial initWithAdUnitID:]: unrecognized selector sent to instance 0x7fa6e0eb2300
2015-07-16 19:43:04.838 TestAndroid-mobile[9001:247857] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GADInterstitial initWithAdUnitID:]: unrecognized selector sent to instance 0x7fa6e0eb2300'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010bc2cc65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010b805bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010bc340ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x000000010bb8a13c ___forwarding_** + 988
    4   CoreFoundation                      0x000000010bb89cd8 _CF_forwarding_prep_0 + 120
    5   TestAndroid-mobile                  0x000000010785cca7 -[IOSHelper requestAdMobFullscreenAd] + 87
    6   TestAndroid-mobile                  0x000000010785b605 -[IOSHelper initialise] + 245
    7   TestAndroid-mobile                  0x00000001078539e9 _ZN12IOSCPPHelper5SetupEv + 41
    8   TestAndroid-mobile                  0x0000000107853d59 _ZN16SonarCocosHelper3IOS5SetupEv + 9
    9   TestAndroid-mobile                  0x00000001078595e3 _ZN10HelloWorld4initEv + 2611
    10  TestAndroid-mobile                  0x00000001078598e6 _ZN10HelloWorld6createEv + 150
    11  TestAndroid-mobile                  0x0000000107858b76 _ZN10HelloWorld11createSceneEv + 22
    12  TestAndroid-mobile                  0x00000001078537c9 _ZN11AppDelegate29applicationDidFinishLaunchingEv + 825
    13  TestAndroid-mobile                  0x00000001078cacf4 _ZN7cocos2d11Application3runEv + 36
    14  TestAndroid-mobile                  0x000000010785b225 -[AppController application:didFinishLaunchingWithOptions:] + 997
    15  UIKit                               0x0000000109ef1748 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 240
    16  UIKit                               0x0000000109ef2357 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2540
    17  UIKit                               0x0000000109ef519e -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
    18  UIKit                               0x0000000109ef4095 -[UIApplication workspaceDidEndTransaction:] + 179
    19  FrontBoardServices                  0x000000010e8b25e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
    20  CoreFoundation                      0x000000010bb6041c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    21  CoreFoundation                      0x000000010bb56165 __CFRunLoopDoBlocks + 341
    22  CoreFoundation                      0x000000010bb55f25 __CFRunLoopRun + 2389
    23  CoreFoundation                      0x000000010bb55366 CFRunLoopRunSpecific + 470
    24  UIKit                               0x0000000109ef3b02 -[UIApplication _run] + 413
    25  UIKit                               0x0000000109ef68c0 UIApplicationMain + 1282
    26  TestAndroid-mobile                  0x000000010785d224 main + 100
    27  libdyld.dylib                       0x000000010c482145 start + 1
    28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by SonarSystems** [comment]
Have you called the Setup method for the Helper?
