### ISSUE TITLE
SonarCocosHelper/SonarFrameworks.h: No such file or directory

### ISSUE THREAD

**Issue by pepeek** [SonarSystems/Cocos-Helper#16]
I'm using cocos2d-js 3.7 and followed your tutorial at: http://www.sonarlearning.co.uk/coursepage.php?topic=game&course=sonar-cocos-helper-js&videoindex=6489#6489

Compilation gives me this error:

```
In file included from jni/../../Classes/JNIResults.cpp:9:0:
jni/../../Classes/JNIResults.h:19:46: fatal error: SonarCocosHelper/SonarFrameworks.h: No such file or directory
 #include "SonarCocosHelper/SonarFrameworks.h"
```

This file sure do include the SonarFrameworks.h which is never referenced in your video.

Please help!

**Comment by SonarSystems** [comment]
It should be ok, have you watched the entire video?

**Comment by pepeek** [comment]
I believe i did. No hint about my problem. What do you mean by "should be ok" ? It is a compilation error. Do you have a hint?

**Comment by pepeek** [comment]
Please, do you have any hint on this? I'm still having the difficulty with the basic setup of CocosHelper on cocos2d-js 3.7 using the `cocos` command line compilation (no IDE used).

**Comment by SonarSystems** [comment]
Try using the the IDE used in the video and let us know how that goes, using an IDE will be needed for other stuff like ads, social etc as you need to link libraries/frameworks inside the IDE.

**Comment by ahmad-raza** [comment]
Change this line:
_#include "SonarCocosHelper/SonarFrameworks.h"_
to
_#include "SonarFrameworks.h"_
in JNIResults file & It will work fine.

I faced this issue, applied some tricks and fixed it by updating that line.
