### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by digitalhoax** [SonarSystems/Cocos-Helper#30]
Hi,

Are there any plans to update the helper for tvOS? I would love to use the Game Center wrapper for both iOS and tvOS.

Cheers,
Lennert

**Comment by SonarSystems** [comment]
We are indeed discussing this, features like this will come when Cocos2d-x fully supports tvOS.

Also if you have any more requests feel free to submit them right here http://www.sonarsystems.co.uk/cocoshelper.php?type=featurerequest
