### ISSUE TITLE
Google Play Services userID

### ISSUE THREAD

**Issue by AlexanderBykin** [SonarSystems/Cocos-Helper#35]
Hi.
Is that possible to get UserID and Name from Google Play Services that i can next use at my server as player login?

**Comment by SonarSystems** [comment]
Not ATM but you can implement it using this link then do a push request :D

http://stackoverflow.com/questions/26413589/get-a-user-id-from-google-play-services

**Comment by AlexanderBykin** [comment]
ok looks like i need to remove helper and replace it with email auth

**Comment by SonarSystems** [comment]
Remove Helper?

**Comment by AlexanderBykin** [comment]
yes cocos helper, because i need "ready to use" features

**Comment by SonarSystems** [comment]
How do you plan on implementing email auth?

**Comment by AlexanderBykin** [comment]
my game is online multiplayer game, so i can send email and encrypted password to server and server then send email verification.

**Comment by SonarSystems** [comment]
I mean in terms of code, do you have another framework to help you integrate it?

**Comment by AlexanderBykin** [comment]
email integration is not problem, i can implement it something about 3-4 hours, because server and client well designed

**Comment by SonarSystems** [comment]
Are you going to implement it natively or using C++ code?

**Comment by AlexanderBykin** [comment]
on client side it is C++ and server is Scala + Akka, communication layer is Protobuf.
as a example of my project you can look at my project:
https://github.com/AlexanderShniperson/cocos2dx_socket_example

**Comment by AlexanderBykin** [comment]
so yes, i will implement it with C++

**Comment by SonarSystems** [comment]
Cool, don't forget the Cocos Helper is an open source collection of plugins, so feel free to integrate cocos2dx socket into Cocos Helper so the entire community can benefit and we would be more than willing to create video tutorials on it.

**Comment by AlexanderBykin** [comment]
ok :) but i dont mind if you integrate it in to CocosHelper, it is also have MIT license.

**Comment by SonarSystems** [comment]
We are very busy ATM integrating other features but in the future it is indeed a possibility.
