### ISSUE TITLE
Virtual onscreen Joystick and Pause popup

### ISSUE THREAD

**Issue by Ratel13** [SonarSystems/Cocos-Helper#42]
Hi,

First I would like to thank you for everything! You are changing my life for sure!!!

Second I would like to recommend this github repository:
    https://github.com/cpinan/BTEndlessTunnel

This game has the Virtual onscreen Joystick and pause popup, I think that this can help!

**Comment by SonarSystems** [comment]
Your welcome, the github page link doesn't work though.

**Comment by Ratel13** [comment]
Is this game:
http://www.carlospinan.com/2014/05/10/un-juego-propio-turbo-race/

**Comment by SonarSystems** [comment]
Thanks for recommending this.

**Comment by Ratel13** [comment]
ok.
