### ISSUE TITLE
Cocos v3.10 compilations fails: SonarFrameworks.h: No such file or directory

### ISSUE THREAD

**Issue by saiy2k** [SonarSystems/Cocos-Helper#46]
Was getting this error with Cocos2dx 3.8 and Cocos Helper v1.48.00 in my Mac!

Then upgraded to Cocos2dx 3.10 and getting the same error. Tried fixing one error and the other error shows up.
- Err1: SonarCocosHelper/SonarFrameworks.h: No such file or directory
  - Copied SonarFrameworks.h, SonarFrameworks.cpp to Classes from /SonarCocosHelperCPP
- Err2: jni/../../Classes/SonarFrameworks.h:23:24: fatal error: JNIHelpers.h: No such file or directory
  - Copied JNIHelpers.h, JNIHelpers.cpp to Classes from /External Cocos Helper Android Frameworks/Classes
- Err3: jni/../../Classes/JNIResults.cpp:30: error: undefined reference to 'SonarCocosHelper::AdMob::showPreLoadedFullscreenAd()' and jni/../../Classes/JNIResults.cpp:41: error: undefined reference to 'SonarCocosHelper::Chartboost::showFullscreenAd()'
  - Updated Android.mk as follows:
  - LOCAL_SRC_FILES := hellojavascript/main.cpp \
  - ../../Classes/AppDelegate.cpp \
  - ../../Classes/JNIResults.cpp \
  - ../../Classes/JNIHelpers.cpp \
  - ../../Classes/SonarFrameworks.cpp
- [aapt] /Users/saiy2k/projects/bonar/frameworks/runtime-src/proj.android/bin/AndroidManifest.xml:2: error: No resource identifier found for attribute 'hardwareAccelerated' in package 'android
  - Removed `android:hardwareAccelerated="true"` from the AndroidManifest.xml

After all this steps, the Project compiled successfully. But on app launch, it shows `Unfortunately, App has stopped`.

Please help.

**Comment by aleksmutlu** [comment]
Same error here... 
I am using cocos2dx 3.10 version, and CocosHelper 1.48 on Mac. I can setup and use CocosHelper for iOS perfectly, but no chance for android version. I repeated the video tutorial 3 times. Always the same error.

**Comment by OscarLeif** [comment]
@saiy2k Are you using the version of cocos2d-x C++ or JS?

**Comment by OscarLeif** [comment]
I no have a lot of experience using cocos2d-js but I was able to compile a hello world project using cocos helper. The only thing that it wasn't in the video was this.
Change this 
`System.loadLibrary("cocos2dcpp");`
with this 
`System.loadLibrary("cocos2djs");`

Oh don't forget to add 
"SonarFrameworks.h"
"SonarFrameworks.cpp"

Also add this files to Android.mk file.

**I only test the install of the cocos helper plugin I didn't use any external framework**
If anyone know a good IDE for cocos2d-js please tell I don't like to use the console a lot :P

**Comment by aleksmutlu** [comment]
Thanks for your respond @OscarLeif :)
I am using the JS version.. 
`System.loadLibrary("cocos2djs");`
I am gonna try this and let you know tomorrow :)

**Comment by saiy2k** [comment]
@OscarLeif Thanks. It's working with the Library change :-)
Terminal / VIM 4 Life :+1:

**Comment by OscarLeif** [comment]
@SonarSystems The problem is solved maybe it will be a good idea to put this in the youtube video

**Comment by aleksmutlu** [comment]
Yeap worked for me too.. :) thanks @OscarLeif !

**Comment by OscarLeif** [comment]
That's good to hear I think I will put a new variable or manifest filer to improve that 
:smile:

**Comment by efares** [comment]
@OscarLeif Where do we add 
"SonarFrameworks.h"
"SonarFrameworks.cpp"

Which directory?

**Comment by elifares** [comment]
@OscarLeif @aleksmutlu @saiy2k Where do you change this 
`System.loadLibrary("cocos2dcpp");`
with this 
`System.loadLibrary("cocos2djs");`

In which file?
Thanks

**Comment by saiy2k** [comment]
@efares 
In the file @ frameworks/runtime-src/proj.android/src/sonar/systems/framework/SonarFrameworkActivity.java

Check the last few lines.

**Comment by elifares** [comment]
Thanks @saiy2k I found it and changed it, it compiles successfully but ran into another problem now. When I open my app on my Android phone it loads the blue debug screen that says "waiting for file transfer..." with the cocos play button on the right. When I click the play button it just zooms in instead of running my game.

Video of the problem I am having now: [Video](https://drive.google.com/file/d/0B23fyDN05oqyQ09USm0tT0ljd28/view?usp=sharing)

SOVLED:
My issue was that I had
"src/SonarFrameworks"
in the jsList instead of 
"src/SonarFrameworks.js" (missing the .js at the end)
