### ISSUE TITLE
IOSHelper.m Property 'viewController' not found on object of type 'AppController *'

### ISSUE THREAD

**Issue by n2oula** [SonarSystems/Cocos-Helper#5]
Using Cocos2d-x CPP 3.3, I am getting the Semantic Issue on compilation on the below lines of IOSHelper.m:

localViewController = appController.viewController;
view = appController.viewController.view;

**Comment by n2oula** [comment]
Solved it.
Had to change my AppController.h from

```
@interface AppController : NSObject <UIApplicationDelegate> {
    UIWindow *window;
    RootViewController    *viewController;
}
```

to

```
@interface AppController : NSObject <UIApplicationDelegate> {
    UIWindow *window;
}
@property(nonatomic, readonly) RootViewController* viewController;
```

**Comment by SonarSystems** [comment]
We know about this and thought it was only with Cocos2d-JS in which we tell the user to do this change. Thanks for bringing this to our attention.
